/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp;
import java.io.*;
import java.net.*;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        // arguments supply message and hostname of destination
        int serverPort = 7896;
        try (Socket s = new Socket("localhost",serverPort)) {
            InputStream in = s.getInputStream();
            OutputStream out = s.getOutputStream();
            boolean keepPlaying = true;
            Scanner sc = new Scanner(System.in);

            out.write(0);
            
            while(keepPlaying){
            int answerServer = in.read();
            if(answerServer==0){
                System.out.println("Bro take a guess [0-9]");
                int guess1= sc.nextInt();
                out.write(guess1);
            } 
            if(answerServer==1){
                System.out.println("You won!");
                System.out.println("Do you want to play again?");
                int playAgain = sc.nextInt();
                if(playAgain==1){
                    keepPlaying=false;
                }
                out.write(playAgain);
            }
            if(answerServer==2){
                System.out.println("Guess again!");
                int guess2 = sc.nextInt();
                out.write(guess2);
            }
            if(answerServer==9){
                System.out.println("You lost :(!");
                System.out.println("Do you want to play again?0:YES || 1:NO");
                int playAgain2 = sc.nextInt();
                if(playAgain2==1){
                    keepPlaying=false;
                }
                out.write(playAgain2);
            }

        }

        }
        catch (UnknownHostException e) {
            System.out.println("Sock:" + e.getMessage());
        } catch (EOFException e) {
            System.out.println("EOF:" + e.getMessage());
        } catch (IOException e) {
            System.out.println("IO:" + e.getMessage());
        }
    }
}
